icecast:
  image: moul/icecast:latest
  volumes:
  - logs:/var/log/icecast2
  - /etc/localtime:/etc/localtime:ro 
  environment:
  - ICECAST_SOURCE_PASSWORD=docker
  - ICECAST_ADMIN_PASSWORD=docker
  - ICECAST_PASSWORD=docker
  - ICECAST_RELAY_PASSWORD=docker
  ports:
  - 8000:8000
